### PR TITLE
Add the social icons 

### PR DESCRIPTION
**Pull request by RizaHKhan**
Lets start small. I noticed the icons were not working. From just a few google searches found out it was a different library and you had to use the font-awesome component with a special syntax with referencing the imported icon.

Hope this is what you wanted here. Please feel free to critique where necessary, I'm definitely not the best developer out there.

Also, my linter just went nuts on a bunch of files. We might need to add a root prettierrc file?

### CODE REVIEW

**Comment by JadRizk** [comment]
Hey man !

Okay so I've added some settings for the linter and formatter. Should be working fine by now.
If you can just rebase the changes run the lint and format command.
I've also added Husky to ensure a good codebase 🐶

Hope this helps 🚀 
Looking forward to see your changes in action 💥

**Comment by RizaHKhan** [comment]
@JadRizk I trying to setup my fork to sync with this repo but it seems not possible without using external libraries? Do you know of a way to sync my master with your master branch?

Alternatively, would you consider giving me contributor access to this repo?

Thanks!

**Comment by RizaHKhan** [comment]
Rebased and ran the requested commands.

The icons work for both registration and login forms (though currently not functional).

**Review by JadRizk — COMMENTED** [review]
💥💥

**Pull request merged**
